### ISSUE TITLE
[Telas 04 e 05, Login e Cadastro]

### ISSUE THREAD

**Issue by jessicagrimaldi** [ICEI-PUC-Minas-PMV-ADS/homePet-FrontEnd#9]
Desenvolver as páginas conforme o Figma do Projeto. ; Atualizar nas pastas correspondentes as telas, localizadas em src > pages (Branch development)

**Comment by robertdolxd1** [comment]
Finalizei os codigos de desenvolvimento em html e css para pagina de login e pagina de cadastro
